### ISSUE TITLE
Preload after timeout

### ISSUE THREAD

**Issue by PeterKottas** [GoogleChromeLabs/preload-webpack-plugin#43]
Hi, I've been experimenting with this lib and so far it seems really straight forward. I have one question though. Is it possible to setup a timeout after which the preloading starts? 

My usecase is:
Let's say I am on slow 3G, the main app is 1.2 mb. Chunks are additional 2mb.
User navigates to the page, it starts loading, but while it loads crucial parts, it starts preloading the additional chunks slowing down the time of first meaningful pain. It would be ideal if it could wait until there's no network traffic but I assume that wouldn't be so straight forward so maybe a timeout at least? 

What do you think?

**Comment by jeffposnick** [comment]
That's unfortunately outside the scope of what we can do in this library. We're building on top of the [web platform's primitives](https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/), and there's no support for configuring a delay in behavior like what you describe.

I'd imagine that for your use case, especially since your payloads are so large, avoiding `<link rel="preload">` entirely wouldn't be a bad idea. Instead, you could load the additional chunks from JavaScript as the last action in your main chunk.
